name: "Hugo on Fire"
description: "A Github action build a Hugo site and then deploy it to Firebase Hosting"
author: "Wajahat Karim (https://wajahatkarim.com)"

branding:
  icon: 'arrow-up-right'
  color: 'red'
  label: 'Hugo On Fire'

inputs:
  firebase_token:
    description: "Firebase token used to deploy on Firebase on your behalf. You can get it using command 'firebase login:ci' and then set it in Github Secrets as FIREBASE_TOKEN variable."
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.firebase_token }}
